server:
  port: ${SERVER_PORT:9999}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jinelei.numbfish.auth.client.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: ${KNIFE4J_ENABLED:true}
  setting:
    language: zh_cn
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: ${KNIFE4J_USERNAME:numbfish}
    # Basic认证密码
    password: ${KNIFE4J_PASSWORD:numbfish}

# Logger Config
logging:
  level:
    root: warn
    com.jinelei: debug

spring:
  application:
    name: numbfish-auth-service
  banner:
    location: banner.txt
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:iotgenius}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      database: ${REDIS_DATABASE:0}
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis:
  mapper-locations: classpath*:mapper/*/*Mapper.xml,classpath*:mapper/*Mapper.xml
  type-handlers-package: com.jinelei.numbfish.auth.client.configuration.handler.type
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
numbfish:
  authorization:
    admin:
      username: admin
    login:
      url: /user/login
    ignore:
      urls:
        - /webjars
        - /doc.html
        - /setup/**
        - /favicon.ico
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html
        - /swagger-resources/**