name: 编译并发布

on:
  push:
    tags:
      - v*.*.*
#on:
#  push:
#    branches:
#      - main

jobs:
  build_api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: 构建工程
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          overwrite-settings: true
      - name: Install dependencies
        run: mvn install -B -DskipTests
      - name: 发布Maven仓库
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_args: '-DskipTests -pl authorization-api'
          maven_profiles: 'release'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.MAVEN_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_PASSWORD }}
          server_id: OSSRH
  build_client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: 构建工程
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          overwrite-settings: true
      - name: Install dependencies
        run: mvn install -B -DskipTests
      - name: 发布Maven仓库
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_args: '-DskipTests -pl authorization-client'
          maven_profiles: 'release'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.MAVEN_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_PASSWORD }}
          server_id: OSSRH